prefix = "."
stop-words = "stopwords.txt"

dataset = "indeed"
corpus = "line.toml"
index = "idx"

# query-judgements = "cranfield-qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = [{type = "icu-tokenizer"}]

# [query-runner]
# query-path = "resume-queries.txt"
# query-id-start = 1
