prefix = "./indeed"
stop-words = "stopwords.txt"

dataset = "sp"
corpus = "line.toml"
index = "idx"

# query-judgements = "cranfield-qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = [{type = "icu-tokenizer"}, 
          {type = "lowercase"}, 
          {type = "length", min = 2, max = 35},
          {type = "list", file = "./indeed/stopwords.txt"},
          {type = "empty-sentence"},
          {type = "porter2-filter"}
          ]

# [query-runner]
# query-path = "resume-queries.txt"
# query-id-start = 1
